services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile

    image: teacher-hub-frontend-dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file: .env
    command: npm run dev
